name: lay
description: "Un nouveau projet Flutter."
# La ligne suivante empêche le package d'être accidentellement publié sur
# pub.dev en utilisant `flutter pub publish`. Cela est préférable pour les packages privés.
publish_to: 'none' # Supprimez cette ligne si vous souhaitez publier sur pub.dev

# La section suivante définit la version et le numéro de build pour votre application.
# Un numéro de version est composé de trois chiffres séparés par des points, comme 1.2.43
# suivi d'un numéro de build optionnel séparé par un +.
# Les numéros de version et de build peuvent être remplacés lors de la construction avec
# les options --build-name et --build-number respectivement.
# Sur Android, build-name est utilisé comme versionName et build-number comme versionCode.
# En savoir plus sur le versioning Android : https://developer.android.com/studio/publish/versioning
# Sur iOS, build-name est utilisé comme CFBundleShortVersionString et build-number comme CFBundleVersion.
# En savoir plus sur le versioning iOS :
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# Sur Windows, build-name est utilisé pour les parties major, minor et patch
# des versions produit et fichier, tandis que build-number est utilisé comme suffixe de build.
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# Les dépendances spécifient les autres packages dont votre package a besoin pour fonctionner.
# Pour mettre à jour automatiquement les dépendances de votre package vers les dernières versions,
# vous pouvez exécuter `flutter pub upgrade --major-versions`. Alternativement,
# les dépendances peuvent être mises à jour manuellement en changeant les numéros de version ci-dessous pour
# la dernière version disponible sur pub.dev. Pour voir quelles dépendances ont des versions plus récentes disponibles,
# exécutez `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # La ligne suivante ajoute la police Cupertino Icons à votre application.
  # Utilisez-la avec la classe CupertinoIcons pour les icônes de style iOS.
  cupertino_icons: ^1.0.6
  printing: ^5.12.0
  image_picker: ^1.1.1
  opencv_4: ^1.0.0
  image_cropper: ^6.0.0
  path_provider: ^2.1.2
  pdf: ^3.10.8
  image_gallery_saver: ^2.0.3
  scribble: ^0.10.0+1
  url_launcher_web: ^2.3.1
  value_notifier_tools: ^0.1.2
  share_plus: ^9.0.0
  file_picker: ^8.0.3
  open_file_manager: ^1.0.2
  flutter_pdfview: ^1.3.2
  pdf_render: ^1.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Le package "flutter_lints" ci-dessous contient un ensemble de lints recommandés
  # pour encourager les bonnes pratiques de codage. L'ensemble de lints fourni par le package est
  # activé dans le fichier `analysis_options.yaml` situé à la racine de votre
  # package. Consultez ce fichier pour des informations sur la désactivation de règles de lint spécifiques
  # et sur l'activation d'autres règles.
  flutter_lints: ^3.0.0

# Pour des informations sur la partie générique Dart de ce fichier, consultez la
# page suivante : https://dart.dev/tools/pub/pubspec

# La section suivante est spécifique aux packages Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/ic_launcher.jpeg
  # Un asset d'image peut référer à une ou plusieurs "variantes" spécifiques à la résolution, voir
  # https://flutter.dev/assets-and-images/#resolution-aware

  # Pour des détails concernant l'ajout d'assets à partir des dépendances de packages, consultez
  # https://flutter.dev/assets-and-images/#from-packages

  # Pour ajouter des polices personnalisées à votre application, ajoutez une section fonts ici,
  # dans cette section "flutter". Chaque entrée dans cette liste doit avoir une clé "family" avec le nom de la famille de polices,
  # et une clé "fonts" avec une liste donnant l'asset et d'autres descripteurs pour la police. Par
  # exemple :
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # Pour des détails concernant les polices à partir des dépendances de packages,
  # consultez https://flutter.dev/custom-fonts/#from-packages
